'use client';

import Link from 'next/link';
import { FileText, UserCheck, ShieldAlert, Scale, AlertTriangle, Bell, MessageSquare, Building2, ArrowRight } from 'lucide-react';

export default function TermsOfServicePage() {
  const lastUpdated = "March 2, 2026";

  const sections = [
    {
      icon: UserCheck,
      title: "Account Terms",
      content: [
        {
          subtitle: "Eligibility",
          text: "You must be at least 18 years old to create an account. By creating an account you represent that you have the legal capacity to enter into a binding agreement."
        },
        {
          subtitle: "Account Types",
          text: "We offer Visitor accounts (free, for buyers and browsers) and Dealer accounts (subscription-based, for professional yacht brokers and sellers). Dealer accounts are subject to the separate Dealer Services Agreement in addition to these General Terms."
        },
        {
          subtitle: "Account Security",
          text: "You are responsible for maintaining the confidentiality of your login credentials and for all activity that occurs under your account. Notify us immediately at support@yachtversal.com if you suspect unauthorized access."
        },
        {
          subtitle: "Account Termination",
          text: "We reserve the right to suspend or terminate accounts that violate these Terms, engage in fraudulent activity, or pose risks to the platform, other users, or third parties. You may delete your account at any time through Account Settings."
        },
        {
          subtitle: "Accurate Information",
          text: "You agree to provide accurate, current, and complete information during registration and to keep it updated. Providing false information may result in immediate account termination."
        }
      ]
    },
    {
      icon: Bell,
      title: "Buyer Features & Responsibilities",
      content: [
        {
          subtitle: "Saved Listings & Search Alerts",
          text: "You may save listings and create search alerts that notify you by email when new matching vessels are listed. You can manage or delete alerts at any time through your account settings. We do not guarantee continuous availability of these features."
        },
        {
          subtitle: "Price Alerts",
          text: "You may subscribe to price-drop notifications on specific listings. Alerts are delivered on a best-effort basis and YachtVersal is not liable for missed or delayed notifications."
        },
        {
          subtitle: "AI-Assisted Search",
          text: "Our platform offers an AI-powered search feature that interprets natural-language queries to suggest relevant listings. AI search results are generated by a large language model and may be incomplete or imprecise. You should not rely solely on AI results when making purchasing decisions. We make no warranties regarding the accuracy or completeness of AI-generated suggestions."
        },
        {
          subtitle: "Inquiries to Dealers",
          text: "When you submit an inquiry or make contact through the platform, your contact information (name, email, phone) is shared with the relevant dealer to facilitate communication. You consent to being contacted by that dealer in response to your inquiry."
        },
        {
          subtitle: "Buyer Due Diligence",
          text: "YachtVersal is a marketplace platform. We are not a party to any purchase transaction. All sales agreements are directly between you and the dealer. We strongly encourage independent surveys, sea trials, title searches, and legal review before any vessel purchase."
        }
      ]
    },
    {
      icon: MessageSquare,
      title: "Platform Messaging",
      content: [
        {
          subtitle: "In-Platform Messaging",
          text: "YachtVersal provides a messaging system to facilitate communication between buyers and dealers. Messages sent through the platform may be retained and reviewed for safety, fraud prevention, and dispute resolution purposes."
        },
        {
          subtitle: "Message Content",
          text: "You must not use the messaging system to send spam, unsolicited commercial communications, or harassing content. Do not transmit sensitive personal or financial information (e.g., credit card numbers, bank details) through the messaging system."
        },
        {
          subtitle: "Communications Consent",
          text: "By creating an account, you agree to receive transactional communications from YachtVersal (e.g., security alerts, inquiry confirmations, billing notices). Marketing communications are optional and can be managed through your preferences."
        }
      ]
    },
    {
      icon: ShieldAlert,
      title: "Prohibited Activities",
      content: [
        {
          subtitle: "Fraudulent Behavior",
          text: "You may not engage in fraudulent activities, misrepresent your identity, provide false information, or attempt to deceive other users or YachtVersal."
        },
        {
          subtitle: "Unauthorized Scraping or Automation",
          text: "You may not use automated systems, bots, scrapers, or crawlers to access the YachtVersal platform without our prior written permission. Programmatic access is available only through our official API under the Dealer Services Agreement."
        },
        {
          subtitle: "Circumventing Security",
          text: "Attempting to gain unauthorized access to any part of the platform, its servers, databases, or connected systems is strictly prohibited and may constitute a criminal offense."
        },
        {
          subtitle: "Content Violations",
          text: "You may not post illegal content, content that infringes intellectual property rights, malware, or material that is defamatory, obscene, or discriminatory."
        },
        {
          subtitle: "Platform Interference",
          text: "You may not take any action that overloads, disrupts, or impairs the proper functioning of the platform or degrades other users' experience."
        }
      ]
    },
    {
      icon: Scale,
      title: "Intellectual Property",
      content: [
        {
          subtitle: "Platform Content",
          text: "All platform content, including text, graphics, logos, software, design, and compiled data, is owned by YachtVersal or its licensors and is protected by copyright, trademark, and other intellectual property laws."
        },
        {
          subtitle: "User-Submitted Content",
          text: "You retain ownership of content you submit. By submitting content, you grant YachtVersal a non-exclusive, worldwide, royalty-free license to use, display, and distribute that content within the platform solely to operate the service."
        },
        {
          subtitle: "Dealer Media",
          text: "Dealers grant additional media rights as described in the Dealer Services Agreement, including use in marketing materials."
        },
        {
          subtitle: "Trademarks",
          text: "YachtVersal, our logo, and related marks are trademarks of YachtVersal. You may not use them without prior written permission."
        },
        {
          subtitle: "DMCA Compliance",
          text: "We respect intellectual property rights. If you believe content on the platform infringes your copyright, contact us at legal@yachtversal.com with a DMCA-compliant takedown notice."
        }
      ]
    },
    {
      icon: AlertTriangle,
      title: "Disclaimers and Limitations of Liability",
      content: [
        {
          subtitle: "No Warranties",
          text: "The platform is provided \"as is\" and \"as available\" without warranties of any kind, express or implied. We do not warrant uninterrupted access, error-free operation, or the accuracy of any listing or AI-generated content."
        },
        {
          subtitle: "Third-Party Content",
          text: "Listings, descriptions, and media are provided by dealers and are their sole responsibility. YachtVersal does not independently verify listing accuracy or vessel condition and makes no representations about the same."
        },
        {
          subtitle: "Third-Party Services",
          text: "The platform integrates with third-party services including Stripe (payments), Anthropic (AI search), OpenStreetMap (mapping), Vercel (hosting), and Render (infrastructure). Your use of these services is also subject to their respective terms and privacy policies."
        },
        {
          subtitle: "Limitation of Liability",
          text: "To the maximum extent permitted by applicable law, YachtVersal shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or goodwill, arising out of your use of or inability to use the platform."
        },
        {
          subtitle: "Indemnification",
          text: "You agree to indemnify and hold harmless YachtVersal and its officers, directors, employees, and agents from any claims, damages, or expenses arising from your use of the platform, your violation of these Terms, or your infringement of any third-party rights."
        }
      ]
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-b from-white via-soft to-white">
      {/* Hero Section */}
      <section className="relative bg-gradient-to-br from-primary/10 via-white to-primary/5 py-20 border-b border-primary/20">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="inline-flex items-center justify-center w-20 h-20 rounded-2xl bg-primary/10 border-2 border-primary/30 mb-6">
            <FileText className="w-10 h-10 text-primary" />
          </div>
          <h1 className="text-5xl md:text-6xl font-bold text-secondary mb-6">
            General Terms of Service
          </h1>
          <p className="text-xl text-dark/70 mb-4">
            These terms apply to all visitors, registered users, and buyers on the YachtVersal platform.
          </p>
          <p className="text-sm text-dark/70">
            Last Updated: <span className="font-semibold">{lastUpdated}</span>
          </p>
        </div>
      </section>

      {/* Content */}
      <section className="py-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">

          {/* Dealer callout banner */}
          <div className="bg-[#10214F] rounded-2xl p-6 mb-10 flex flex-col sm:flex-row items-start sm:items-center gap-4">
            <div className="w-12 h-12 rounded-xl bg-white/10 border border-white/20 flex items-center justify-center flex-shrink-0">
              <Building2 className="w-6 h-6 text-[#01BBDC]" />
            </div>
            <div className="flex-1">
              <p className="font-bold text-white text-lg leading-tight mb-1">Are you a Yacht Broker or Dealer?</p>
              <p className="text-white/70 text-sm leading-relaxed">
                In addition to these General Terms, dealer accounts are governed by the{' '}
                <Link href="/terms/dealer" className="text-[#01BBDC] underline font-semibold">Dealer Services Agreement</Link>,
                which covers listing standards, website data import authorization, API co-brokering rights, media licensing, and subscription billing.
                You must read and accept both documents.
              </p>
            </div>
            <Link
              href="/terms/dealer"
              className="flex items-center gap-2 px-5 py-2.5 rounded-xl font-semibold text-sm flex-shrink-0 transition-opacity hover:opacity-90"
              style={{ backgroundColor: '#01BBDC', color: '#fff' }}
            >
              Dealer Agreement <ArrowRight className="w-4 h-4" />
            </Link>
          </div>

          {/* Introduction */}
          <div className="bg-white rounded-2xl shadow-sm border border-gray-200 p-8 mb-12">
            <h2 className="text-2xl font-bold text-secondary mb-4">Agreement to Terms</h2>
            <p className="text-dark leading-relaxed mb-4">
              These General Terms of Service ("Terms") govern your access to and use of the YachtVersal website, mobile application, and related services (collectively, the "Platform"). This is a binding legal agreement between you and YachtVersal.
            </p>
            <p className="text-dark leading-relaxed mb-4">
              By accessing or using the Platform, you acknowledge that you have read, understood, and agree to be bound by these Terms and our <Link href="/privacy" className="text-primary underline">Privacy Policy</Link>. If you do not agree, you must not access or use the Platform.
            </p>
            <p className="text-dark leading-relaxed">
              <strong>Dealers and professional brokers</strong> must additionally read and accept the{' '}
              <Link href="/terms/dealer" className="text-primary underline">Dealer Services Agreement</Link>, which contains terms specific to listing, billing, data import, co-brokering, and media usage.
            </p>
          </div>

          {/* Main Sections */}
          <div className="space-y-12">
            {sections.map((section, idx) => (
              <div key={idx} className="bg-white rounded-2xl shadow-sm border border-gray-200 overflow-hidden">
                <div className="bg-gradient-to-r from-primary/10 to-primary/5 p-6 border-b border-gray-200">
                  <div className="flex items-center gap-4">
                    <div className="w-12 h-12 rounded-xl bg-primary/20 border border-primary/30 flex items-center justify-center">
                      <section.icon className="w-6 h-6 text-primary" />
                    </div>
                    <h2 className="text-2xl font-bold text-secondary">{section.title}</h2>
                  </div>
                </div>
                
                <div className="p-8 space-y-6">
                  {section.content.map((item, itemIdx) => (
                    <div key={itemIdx}>
                      <h3 className="text-lg font-semibold text-secondary mb-3">
                        {item.subtitle}
                      </h3>
                      <p className="text-dark leading-relaxed">
                        {item.text}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>

          {/* Governing Law */}
          <div className="bg-gradient-to-br from-section-light to-white rounded-2xl p-8 mt-12 border border-gray-200">
            <h2 className="text-2xl font-bold text-secondary mb-4">Governing Law and Disputes</h2>
            <div className="space-y-4 text-dark leading-relaxed">
              <p>
                These Terms shall be governed by the laws of the State of Florida, United States, without regard to its conflict-of-law provisions.
              </p>
              <p>
                Any disputes arising from these Terms or your use of the Platform shall be resolved through binding arbitration in accordance with the rules of the American Arbitration Association. You waive any right to a jury trial or class action participation.
              </p>
            </div>
          </div>

          {/* Modifications */}
          <div className="bg-amber-50 border border-amber-200 rounded-2xl p-8 mt-8">
            <h2 className="text-2xl font-bold text-secondary mb-4">Modifications to Terms</h2>
            <p className="text-dark leading-relaxed">
              We reserve the right to modify these Terms at any time. We will notify users of material changes via email or platform notification at least 14 days before they take effect. Your continued use of the Platform after a change constitutes acceptance of the updated Terms.
            </p>
          </div>

          {/* Severability */}
          <div className="bg-blue-50 border border-blue-200 rounded-2xl p-8 mt-8">
            <h2 className="text-2xl font-bold text-secondary mb-4">Severability</h2>
            <p className="text-dark leading-relaxed">
              If any provision of these Terms is found to be unenforceable, that provision will be limited or eliminated to the minimum extent necessary so that these Terms otherwise remain in full force and effect.
            </p>
          </div>

          {/* Dealer Agreement CTA */}
          <div className="bg-[#10214F] rounded-2xl p-8 mt-8 flex flex-col sm:flex-row items-center gap-6">
            <div className="flex-1">
              <p className="text-white font-bold text-xl mb-2">Professional Broker or Dealer?</p>
              <p className="text-white/70 text-sm leading-relaxed">
                Your use of the platform is also governed by our Dealer Services Agreement, covering data import authorization, co-brokering, media rights, API usage, and subscription billing.
              </p>
            </div>
            <Link
              href="/terms/dealer"
              className="flex items-center gap-2 px-6 py-3 rounded-xl font-semibold text-sm flex-shrink-0 transition-opacity hover:opacity-90 whitespace-nowrap"
              style={{ backgroundColor: '#01BBDC', color: '#fff' }}
            >
              Read Dealer Services Agreement <ArrowRight className="w-4 h-4" />
            </Link>
          </div>

          {/* Contact Section */}
          <div className="bg-gradient-to-br from-primary/10 to-primary/5 rounded-2xl p-8 mt-8 border border-primary/20">
            <h2 className="text-2xl font-bold text-secondary mb-4">Questions About These Terms?</h2>
            <p className="text-dark leading-relaxed mb-4">
              If you have questions about these General Terms of Service, please contact us:
            </p>
            <div className="space-y-2 text-dark">
              <p><strong>Email:</strong> legal@yachtversal.com</p>
              <p><strong>Mail:</strong> YachtVersal Legal Department, [Address], [City, State ZIP]</p>
            </div>
          </div>

        </div>
      </section>
    </div>
  );
}