"""
Demo account fixtures and sample listing data.
Used to populate demo dealer accounts with showcase listings.

Status distribution across the 9 fixtures:
  - active (5): visible in All / Active tabs, showcases listings in action
  - featured (1): active + featured=True, showcases the Featured Listings tab
  - sold (1): showcases the Sold tab
  - draft (1): showcases the Draft tab
  - needs_approval (1): showcases the Needs Approval tab
  - recently_deleted=True (1 of the actives): soft-deleted post-creation to
    showcase the Recently Deleted tab with the 30-day recovery countdown
"""

DEMO_SAMPLE_LISTINGS = [
    # --- Featured showcase ---
    {
        "title": "2024 Azimut 55 - Luxury Motor Yacht",
        "description": "Stunning 55-foot Azimut with state-of-the-art navigation, luxurious cabin, and professional crew quarters. Recently refitted with new electronics and upholstery. Perfect for Mediterranean cruising.",
        "make": "Azimut",
        "model": "55",
        "year": 2024,
        "length_feet": 55,
        "beam_feet": 15,
        "draft_feet": 4.5,
        "price": 2500000,
        "condition": "Excellent",
        "location": "Miami, Florida",
        "boat_type": "motor_yacht",
        "fuel_type": "diesel",
        "num_cabins": 3,
        "num_heads": 3,
        "water_capacity_gallons": 1500,
        "fuel_capacity_gallons": 3000,
        "features": ["GPS", "Radar", "Autopilot", "Stabilizers", "AC/Heating", "Generator", "Water Maker", "Satellite TV", "Tender with Outboard"],
        "status": "active",
        "featured": True,      # showcases Featured Listings tab
        "views": 847,
        "inquiries": 12,
    },
    # --- Active listings ---
    {
        "title": "2022 Sunseeker 76 - Express Cruiser",
        "description": "Luxurious 76-foot Sunseeker with open flybridge and spacious salon. Twin Caterpillar engines provide excellent fuel efficiency. Full spa with hot tub on sundeck.",
        "make": "Sunseeker",
        "model": "76",
        "year": 2022,
        "length_feet": 76,
        "beam_feet": 18,
        "draft_feet": 5.2,
        "price": 3800000,
        "condition": "Excellent",
        "location": "Fort Lauderdale, Florida",
        "boat_type": "motor_yacht",
        "fuel_type": "diesel",
        "num_cabins": 4,
        "num_heads": 4,
        "water_capacity_gallons": 2000,
        "fuel_capacity_gallons": 4000,
        "features": ["Twin Cats", "Bowthruster", "Dynamic Positioning", "Stabilizers", "Full A/C", "Generator", "Watermaker", "Satellite Comms", "Hot Tub", "Gym"],
        "status": "active",
        "featured": False,
        "views": 512,
        "inquiries": 7,
    },
    {
        "title": "2021 Lagoon 450 - Sailing Catamaran",
        "description": "Award-winning 45-foot sailing catamaran. Ideal for cruising or charter. Twin daggerboards for excellent windward performance. Recently hauled and painted.",
        "make": "Lagoon",
        "model": "450",
        "year": 2021,
        "length_feet": 45,
        "beam_feet": 24,
        "draft_feet": 3.5,
        "price": 850000,
        "condition": "Very Good",
        "location": "St. Thomas, USVI",
        "boat_type": "sailing_catamaran",
        "fuel_type": "diesel",
        "num_cabins": 3,
        "num_heads": 3,
        "water_capacity_gallons": 250,
        "fuel_capacity_gallons": 100,
        "features": ["Furling Sails", "Electric Winches", "Autopilot", "GPS/Chartplotter", "VHF", "Generator", "Dinghy"],
        "status": "active",
        "featured": False,
        "views": 234,
        "inquiries": 3,
    },
    {
        "title": "2023 Jeanneau 64 - Performance Cruising Yacht",
        "description": "Sleek 64-foot Jeanneau with excellent performance and comfort. Modern design with spacious cabins and sophisticated navigation suite.",
        "make": "Jeanneau",
        "model": "64",
        "year": 2023,
        "length_feet": 64,
        "beam_feet": 17,
        "draft_feet": 4.8,
        "price": 2200000,
        "condition": "Excellent",
        "location": "Newport, Rhode Island",
        "boat_type": "sailing_yacht",
        "fuel_type": "diesel",
        "num_cabins": 4,
        "num_heads": 3,
        "water_capacity_gallons": 400,
        "fuel_capacity_gallons": 500,
        "features": ["Furling Sails", "In-boom Furler", "Autopilot", "Full A/C", "Generator", "Watermaker"],
        "status": "active",
        "featured": False,
        "views": 156,
        "inquiries": 2,
    },
    # --- Sold listing (showcases Sold tab) ---
    {
        "title": "2019 Sea Ray 460 Sundancer - Spacious Cruiser",
        "description": "Beautiful 46-foot Sea Ray Sundancer with open galley and updated furnishings. Twin Cummins engines. Great for weekenders or liveaboard.",
        "make": "Sea Ray",
        "model": "460 Sundancer",
        "year": 2019,
        "length_feet": 46,
        "beam_feet": 14,
        "draft_feet": 4.2,
        "price": 1200000,
        "condition": "Good",
        "location": "San Diego, California",
        "boat_type": "motor_yacht",
        "fuel_type": "diesel",
        "num_cabins": 2,
        "num_heads": 2,
        "water_capacity_gallons": 800,
        "fuel_capacity_gallons": 2400,
        "features": ["Twin Engines", "Bowthruster", "A/C", "Generator", "Hardtop", "Enclosure", "Dinghy Davit"],
        "status": "sold",       # showcases Sold tab
        "featured": False,
        "views": 189,
        "inquiries": 5,
    },
    # --- Draft listing (showcases Draft tab) ---
    {
        "title": "2020 Beneteau Swift Trawler 50 - Trawler Yacht",
        "description": "Economical 50-foot trawler with excellent sea keeper design. Perfect for world cruising. Low fuel consumption with heavy displacement hull. Listing in progress.",
        "make": "Beneteau",
        "model": "Swift Trawler 50",
        "year": 2020,
        "length_feet": 50,
        "beam_feet": 15,
        "draft_feet": 4.5,
        "price": 980000,
        "condition": "Very Good",
        "location": "Seattle, Washington",
        "boat_type": "trawler",
        "fuel_type": "diesel",
        "num_cabins": 3,
        "num_heads": 3,
        "water_capacity_gallons": 500,
        "fuel_capacity_gallons": 1600,
        "features": ["Single Engine", "Stabilizers", "A/C", "Generator", "Watermaker", "Tender", "Fishing Gear"],
        "status": "draft",      # showcases Draft tab
        "featured": False,
        "views": 0,
        "inquiries": 0,
    },
    # --- Needs Approval listing (showcases Needs Approval tab) ---
    {
        "title": "2023 Princess 68 Flybridge - Luxury Motor Yacht",
        "description": "Latest generation Princess with innovative design. Expansive saloon with floor-to-ceiling windows. Twin Rolls-Royce engines. Pending broker review.",
        "make": "Princess",
        "model": "68 Flybridge",
        "year": 2023,
        "length_feet": 68,
        "beam_feet": 17,
        "draft_feet": 4.9,
        "price": 4500000,
        "condition": "Excellent",
        "location": "Antibes, France",
        "boat_type": "motor_yacht",
        "fuel_type": "diesel",
        "num_cabins": 4,
        "num_heads": 4,
        "water_capacity_gallons": 2000,
        "fuel_capacity_gallons": 4500,
        "features": ["Twin Rolls-Royce", "Dynamic Positioning", "Smart Glass", "Spa Pool", "Sauna", "Elevator", "Tender with Jet"],
        "status": "needs_approval",  # showcases Needs Approval tab
        "featured": False,
        "views": 67,
        "inquiries": 1,
    },
    # --- Active listing that gets soft-deleted to showcase Recently Deleted tab ---
    {
        "title": "2018 Riviera 445 SUV - Sport Utility Vessel",
        "description": "Premium 44-foot Riviera with distinctive SUV styling. Outstanding offshore performance with exceptional range and seakeeping ability.",
        "make": "Riviera",
        "model": "445 SUV",
        "year": 2018,
        "length_feet": 44,
        "beam_feet": 14,
        "draft_feet": 1.3,
        "price": 695000,
        "condition": "Good",
        "location": "Gold Coast, Australia",
        "boat_type": "motor_yacht",
        "fuel_type": "diesel",
        "num_cabins": 2,
        "num_heads": 2,
        "water_capacity_gallons": 600,
        "fuel_capacity_gallons": 1800,
        "features": ["Twin Volvo IPS", "Joystick Docking", "Bowthruster", "A/C", "Generator", "Hardtop"],
        "status": "active",
        "featured": False,
        "views": 91,
        "inquiries": 0,
        "recently_deleted": True,  # soft-deleted after creation to showcase Recently Deleted tab
    },
    # --- A second recently-deleted listing for more realistic Recently Deleted tab ---
    {
        "title": "2020 Beneteau Oceanis 46.1 - Sailing Yacht",
        "description": "Well-appointed 46-foot cruising yacht with excellent offshore capability. Comfort-oriented interior designed for long passages.",
        "make": "Beneteau",
        "model": "Oceanis 46.1",
        "year": 2020,
        "length_feet": 46,
        "beam_feet": 14.4,
        "draft_feet": 6.2,
        "price": 395000,
        "condition": "Very Good",
        "location": "Annapolis, Maryland",
        "boat_type": "sailing_yacht",
        "fuel_type": "diesel",
        "num_cabins": 3,
        "num_heads": 2,
        "water_capacity_gallons": 185,
        "fuel_capacity_gallons": 68,
        "features": ["Self-Tacking Jib", "Autopilot", "Chartplotter", "AIS", "VHF", "Windlass", "Bimini"],
        "status": "active",
        "featured": False,
        "views": 44,
        "inquiries": 0,
        "recently_deleted": True,  # soft-deleted 12 days ago — shows amber countdown
    },
]


def get_demo_listing_data(index: int = None):
    """
    Get demo listing data by index, or all if index is None.
    """
    if index is not None and 0 <= index < len(DEMO_SAMPLE_LISTINGS):
        return DEMO_SAMPLE_LISTINGS[index]
    return DEMO_SAMPLE_LISTINGS
