"""
Demo account fixtures and sample listing data.
Used to populate demo dealer accounts with showcase listings.
"""

DEMO_SAMPLE_LISTINGS = [
    {
        "title": "2024 Azimut 55 - Luxury Motor Yacht",
        "description": "Stunning 55-foot Azimut with state-of-the-art navigation, luxurious cabin, and professional crew quarters. Recently refitted with new electronics and upholstery. Perfect for Mediterranean cruising.",
        "make_model": "Azimut 55",
        "year": 2024,
        "length_feet": 55,
        "beam_feet": 15,
        "draft_feet": 4.5,
        "price": 2500000,
        "price_currency": "USD",
        "condition": "Excellent",
        "location": "Miami, Florida",
        "boat_type": "motor_yacht",
        "fuel_type": "diesel",
        "num_cabins": 3,
        "num_heads": 3,
        "water_capacity_gallons": 1500,
        "fuel_capacity_gallons": 3000,
        "features": ["GPS", "Radar", "Autopilot", "Stabilizers", "AC/Heating", "Generator", "Water Maker", "Satellite TV", "Tender with Outboard"],
    },
    {
        "title": "2022 Sunseeker 76 - Express Cruiser",
        "description": "Luxurious 76-foot Sunseeker with open flybridge and spacious salon. Twin Caterpillar engines provide excellent fuel efficiency. Full spa with hot tub on sundeck.",
        "make_model": "Sunseeker 76",
        "year": 2022,
        "length_feet": 76,
        "beam_feet": 18,
        "draft_feet": 5.2,
        "price": 3800000,
        "price_currency": "USD",
        "condition": "Excellent",
        "location": "Fort Lauderdale, Florida",
        "boat_type": "motor_yacht",
        "fuel_type": "diesel",
        "num_cabins": 4,
        "num_heads": 4,
        "water_capacity_gallons": 2000,
        "fuel_capacity_gallons": 4000,
        "features": ["Twin Cats", "Bowthruster", "Dynamic Positioning", "Stabilizers", "Full A/C", "Generator", "Watermaker", "Satellite Comms", "Hot Tub", "Gym"],
    },
    {
        "title": "2021 Lagoon 450 - Sailing Catamaran",
        "description": "Award-winning 45-foot sailing catamaran. Ideal for cruising or charter. Twin daggerboards for excellent windward performance. Recently hauled and painted.",
        "make_model": "Lagoon 450",
        "year": 2021,
        "length_feet": 45,
        "beam_feet": 24,
        "draft_feet": 3.5,
        "price": 850000,
        "price_currency": "USD",
        "condition": "Very Good",
        "location": "Caribbean",
        "boat_type": "sailing_catamaran",
        "fuel_type": "diesel",
        "num_cabins": 3,
        "num_heads": 3,
        "water_capacity_gallons": 250,
        "fuel_capacity_gallons": 100,
        "features": ["Furling Sails", "Electric Winches", "Autopilot", "GPS/Chartplotter", "VHF", "Generator", "Dinghy"],
    },
    {
        "title": "2019 Sea Ray 460 Sundancer - Spacious Cruiser",
        "description": "Beautiful 46-foot Sea Ray Sundancer with open galley and updated furnishings. Twin Cummins engines. Great for weekender or liveaboard.",
        "make_model": "Sea Ray 460 Sundancer",
        "year": 2019,
        "length_feet": 46,
        "beam_feet": 14,
        "draft_feet": 4.2,
        "price": 1200000,
        "price_currency": "USD",
        "condition": "Good",
        "location": "San Diego, California",
        "boat_type": "motor_yacht",
        "fuel_type": "diesel",
        "num_cabins": 2,
        "num_heads": 2,
        "water_capacity_gallons": 800,
        "fuel_capacity_gallons": 2400,
        "features": ["Twin Engines", "Bowthruster", "A/C", "Generator", "Hardtop", "Enclosure", "Dinghy Davit"],
    },
    {
        "title": "2023 Jeanneau 64 - Performance Cruising Yacht",
        "description": "Sleek 64-foot Jeanneau with excellent performance and comfort. Modern design with spacious cabins and sophisticated navigation suite.",
        "make_model": "Jeanneau 64",
        "year": 2023,
        "length_feet": 64,
        "beam_feet": 17,
        "draft_feet": 4.8,
        "price": 2200000,
        "price_currency": "USD",
        "condition": "Excellent",
        "location": "Newport, Rhode Island",
        "boat_type": "sailing_yacht",
        "fuel_type": "diesel",
        "num_cabins": 4,
        "num_heads": 3,
        "water_capacity_gallons": 400,
        "fuel_capacity_gallons": 500,
        "features": ["Furling Sails", "In-boom Furler", "Autopilot", "Hamilton Jet Drive", "Full A/C", "Generator", "Watermaker"],
    },
    {
        "title": "2020 Beneteau Swift Trawler 50 - Trawler Yacht",
        "description": "Economical 50-foot trawler with excellent sea keeper design. Perfect for world cruising. Low fuel consumption with heavy displacement hull.",
        "make_model": "Beneteau Swift Trawler 50",
        "year": 2020,
        "length_feet": 50,
        "beam_feet": 15,
        "draft_feet": 4.5,
        "price": 980000,
        "price_currency": "USD",
        "condition": "Very Good",
        "location": "Pacific Northwest",
        "boat_type": "trawler",
        "fuel_type": "diesel",
        "num_cabins": 3,
        "num_heads": 3,
        "water_capacity_gallons": 500,
        "fuel_capacity_gallons": 1600,
        "features": ["Single Engine", "Stabilizers", "A/C", "Generator", "Watermaker", "Tender", "Fishing Gear"],
    },
    {
        "title": "2023 Princess 68 Flybridge - Luxury Motor Yacht",
        "description": "Latest generation Princess with innovative design. Expansive saloon with floor-to-ceiling windows. Twin Rolls-Royce engines.",
        "make_model": "Princess 68",
        "year": 2023,
        "length_feet": 68,
        "beam_feet": 17,
        "draft_feet": 4.9,
        "price": 4500000,
        "price_currency": "USD",
        "condition": "Excellent",
        "location": "Antibes, France",
        "boat_type": "motor_yacht",
        "fuel_type": "diesel",
        "num_cabins": 4,
        "num_heads": 4,
        "water_capacity_gallons": 2000,
        "fuel_capacity_gallons": 4500,
        "features": ["Twin Rolls-Royce", "Dynamic Positioning", "Smart Glass", "Spa Pool", "Sauna", "Elevator", "Tender with Jet"],
    },
    {
        "title": "2018 Zodiac Yachtline 480 - Luxury Tender",
        "description": "Impressive 48-foot Zodiac tender with luxury features. Great for beach club or water sports. Volvo D6 engines.",
        "make_model": "Zodiac Yachtline 480",
        "year": 2018,
        "length_feet": 48,
        "beam_feet": 17,
        "draft_feet": 1.5,
        "price": 450000,
        "price_currency": "USD",
        "condition": "Good",
        "location": "Monaco",
        "boat_type": "rigid_inflatable",
        "fuel_type": "diesel",
        "num_cabins": 0,
        "num_heads": 1,
        "water_capacity_gallons": 150,
        "fuel_capacity_gallons": 600,
        "features": ["Twin Engines", "Jet Tender", "Soft Goods Canopy", "Electronics Package", "Tender Garage Ready"],
    },
]


def get_demo_listing_data(index: int = None):
    """
    Get demo listing data by index, or all if index is None.
    """
    if index is not None and 0 <= index < len(DEMO_SAMPLE_LISTINGS):
        return DEMO_SAMPLE_LISTINGS[index]
    return DEMO_SAMPLE_LISTINGS
