// Shared location data for country/state selectors across the app

export const COUNTRIES: string[] = [
  'United States',
  'Canada',
  'Mexico',
  'Bahamas',
  'Bermuda',
  'Cayman Islands',
  'British Virgin Islands',
  'US Virgin Islands',
  'Puerto Rico',
  'Barbados',
  'Trinidad and Tobago',
  'Aruba',
  'Curacao',
  'Antigua and Barbuda',
  'St. Martin',
  'Martinique',
  'Guadeloupe',
  'St. Lucia',
  'Grenada',
  'St. Kitts and Nevis',
  'St. Vincent and the Grenadines',
  'Turks and Caicos',
  'Jamaica',
  'Dominican Republic',
  'Haiti',
  'Cuba',
  'Belize',
  'Guatemala',
  'Honduras',
  'Panama',
  'Colombia',
  'Venezuela',
  'Guyana',
  'Suriname',
  'Brazil',
  'Uruguay',
  'Argentina',
  'Chile',
  'Peru',
  'Ecuador',
  'United Kingdom',
  'Ireland',
  'France',
  'Spain',
  'Portugal',
  'Italy',
  'Greece',
  'Croatia',
  'Montenegro',
  'Albania',
  'Slovenia',
  'Malta',
  'Cyprus',
  'Monaco',
  'Corsica',
  'Sardinia',
  'Sicily',
  'Netherlands',
  'Belgium',
  'Germany',
  'Denmark',
  'Sweden',
  'Norway',
  'Finland',
  'Estonia',
  'Latvia',
  'Lithuania',
  'Poland',
  'Switzerland',
  'Austria',
  'Turkey',
  'Israel',
  'Lebanon',
  'Egypt',
  'Libya',
  'Tunisia',
  'Algeria',
  'Morocco',
  'United Arab Emirates',
  'Oman',
  'Qatar',
  'Bahrain',
  'Kuwait',
  'Saudi Arabia',
  'Yemen',
  'Maldives',
  'India',
  'Sri Lanka',
  'Thailand',
  'Malaysia',
  'Singapore',
  'Indonesia',
  'Philippines',
  'Vietnam',
  'Cambodia',
  'Myanmar',
  'Brunei',
  'Hong Kong',
  'Japan',
  'Taiwan',
  'South Korea',
  'China',
  'Australia',
  'New Zealand',
  'Fiji',
  'Vanuatu',
  'Tonga',
  'Samoa',
  'French Polynesia',
  'New Caledonia',
  'Papua New Guinea',
  'South Africa',
  'Mozambique',
  'Tanzania',
  'Kenya',
  'Seychelles',
  'Mauritius',
  'Réunion',
  'Madagascar',
  'Namibia',
  'Nigeria',
  'Ghana',
  'Senegal',
  'Ivory Coast',
];

// States / provinces / territories for countries that have them
export const STATES_BY_COUNTRY: Record<string, string[]> = {
  'United States': [
    'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
    'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia',
    'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa',
    'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
    'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri',
    'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey',
    'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio',
    'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina',
    'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont',
    'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming',
    'District of Columbia', 'Puerto Rico', 'US Virgin Islands', 'Guam',
    'American Samoa', 'Northern Mariana Islands',
  ],
  'Canada': [
    'Alberta', 'British Columbia', 'Manitoba', 'New Brunswick',
    'Newfoundland and Labrador', 'Northwest Territories', 'Nova Scotia',
    'Nunavut', 'Ontario', 'Prince Edward Island', 'Quebec',
    'Saskatchewan', 'Yukon',
  ],
  'Australia': [
    'Australian Capital Territory', 'New South Wales', 'Northern Territory',
    'Queensland', 'South Australia', 'Tasmania', 'Victoria', 'Western Australia',
  ],
  'United Kingdom': [
    'England', 'Scotland', 'Wales', 'Northern Ireland',
  ],
  'Germany': [
    'Baden-Württemberg', 'Bavaria', 'Berlin', 'Brandenburg', 'Bremen',
    'Hamburg', 'Hesse', 'Lower Saxony', 'Mecklenburg-Vorpommern',
    'North Rhine-Westphalia', 'Rhineland-Palatinate', 'Saarland',
    'Saxony', 'Saxony-Anhalt', 'Schleswig-Holstein', 'Thuringia',
  ],
  'Spain': [
    'Andalusia', 'Aragon', 'Asturias', 'Balearic Islands', 'Basque Country',
    'Canary Islands', 'Cantabria', 'Castile and León', 'Castile-La Mancha',
    'Catalonia', 'Extremadura', 'Galicia', 'La Rioja', 'Madrid',
    'Murcia', 'Navarre', 'Valencia',
  ],
  'Italy': [
    'Abruzzo', 'Basilicata', 'Calabria', 'Campania', 'Emilia-Romagna',
    'Friuli-Venezia Giulia', 'Lazio', 'Liguria', 'Lombardy', 'Marche',
    'Molise', 'Piedmont', 'Puglia', 'Sardinia', 'Sicily',
    'Trentino-Alto Adige', 'Tuscany', 'Umbria', 'Valle d\'Aosta', 'Veneto',
  ],
  'France': [
    'Auvergne-Rhône-Alpes', 'Bourgogne-Franche-Comté', 'Brittany',
    'Centre-Val de Loire', 'Corsica', 'Grand Est', 'Hauts-de-France',
    'Île-de-France', 'Normandy', 'Nouvelle-Aquitaine', 'Occitanie',
    'Pays de la Loire', "Provence-Alpes-Côte d'Azur",
  ],
  'Greece': [
    'Attica', 'Central Greece', 'Central Macedonia', 'Crete',
    'East Macedonia and Thrace', 'Epirus', 'Ionian Islands',
    'North Aegean', 'Peloponnese', 'South Aegean',
    'Thessaly', 'West Greece', 'West Macedonia',
  ],
  'Croatia': [
    'Bjelovar-Bilogora', 'Brod-Posavina', 'Dubrovnik-Neretva', 'Istria',
    'Karlovac', 'Koprivnica-Križevci', 'Krapina-Zagorje', 'Lika-Senj',
    'Međimurje', 'Osijek-Baranja', 'Požega-Slavonia', 'Primorje-Gorski Kotar',
    'Šibenik-Knin', 'Sisak-Moslavina', 'Split-Dalmatia', 'Varaždin',
    'Virovitica-Podravina', 'Vukovar-Srijem', 'Zadar', 'Zagreb County', 'Zagreb',
  ],
  'Mexico': [
    'Aguascalientes', 'Baja California', 'Baja California Sur', 'Campeche',
    'Chiapas', 'Chihuahua', 'Coahuila', 'Colima', 'Durango', 'Guanajuato',
    'Guerrero', 'Hidalgo', 'Jalisco', 'Mexico City', 'Mexico State',
    'Michoacán', 'Morelos', 'Nayarit', 'Nuevo León', 'Oaxaca',
    'Puebla', 'Querétaro', 'Quintana Roo', 'San Luis Potosí', 'Sinaloa',
    'Sonora', 'Tabasco', 'Tamaulipas', 'Tlaxcala', 'Veracruz',
    'Yucatán', 'Zacatecas',
  ],
  'Brazil': [
    'Acre', 'Alagoas', 'Amapá', 'Amazonas', 'Bahia', 'Ceará',
    'Distrito Federal', 'Espírito Santo', 'Goiás', 'Maranhão',
    'Mato Grosso', 'Mato Grosso do Sul', 'Minas Gerais', 'Pará',
    'Paraíba', 'Paraná', 'Pernambuco', 'Piauí', 'Rio de Janeiro',
    'Rio Grande do Norte', 'Rio Grande do Sul', 'Rondônia', 'Roraima',
    'Santa Catarina', 'São Paulo', 'Sergipe', 'Tocantins',
  ],
  'New Zealand': [
    'Auckland', 'Bay of Plenty', 'Canterbury', 'Gisborne', "Hawke's Bay",
    'Manawatu-Whanganui', 'Marlborough', 'Nelson', 'Northland', 'Otago',
    'Southland', 'Taranaki', 'Tasman', 'Waikato', 'Wellington',
    'West Coast',
  ],
  'South Africa': [
    'Eastern Cape', 'Free State', 'Gauteng', 'KwaZulu-Natal', 'Limpopo',
    'Mpumalanga', 'Northern Cape', 'North West', 'Western Cape',
  ],
  'United Arab Emirates': [
    'Abu Dhabi', 'Ajman', 'Dubai', 'Fujairah', 'Ras Al Khaimah',
    'Sharjah', 'Umm Al Quwain',
  ],
};

/** Maps every country in COUNTRIES to its Yachtversal continent label. */
export const COUNTRY_TO_CONTINENT: Record<string, string> = {
  // North America
  'United States': 'North America',
  'Canada': 'North America',
  'Mexico': 'North America',
  'Belize': 'North America',
  'Guatemala': 'North America',
  'Honduras': 'North America',
  'Panama': 'North America',
  // Caribbean
  'Bahamas': 'Caribbean',
  'Bermuda': 'Caribbean',
  'Cayman Islands': 'Caribbean',
  'British Virgin Islands': 'Caribbean',
  'US Virgin Islands': 'Caribbean',
  'Puerto Rico': 'Caribbean',
  'Barbados': 'Caribbean',
  'Trinidad and Tobago': 'Caribbean',
  'Aruba': 'Caribbean',
  'Curacao': 'Caribbean',
  'Antigua and Barbuda': 'Caribbean',
  'St. Martin': 'Caribbean',
  'Martinique': 'Caribbean',
  'Guadeloupe': 'Caribbean',
  'St. Lucia': 'Caribbean',
  'Grenada': 'Caribbean',
  'St. Kitts and Nevis': 'Caribbean',
  'St. Vincent and the Grenadines': 'Caribbean',
  'Turks and Caicos': 'Caribbean',
  'Jamaica': 'Caribbean',
  'Dominican Republic': 'Caribbean',
  'Haiti': 'Caribbean',
  'Cuba': 'Caribbean',
  // South America
  'Colombia': 'South America',
  'Venezuela': 'South America',
  'Guyana': 'South America',
  'Suriname': 'South America',
  'Brazil': 'South America',
  'Uruguay': 'South America',
  'Argentina': 'South America',
  'Chile': 'South America',
  'Peru': 'South America',
  'Ecuador': 'South America',
  // Europe (Atlantic / North Sea)
  'United Kingdom': 'Europe',
  'Ireland': 'Europe',
  'France': 'Europe',
  'Spain': 'Europe',
  'Portugal': 'Europe',
  'Netherlands': 'Europe',
  'Belgium': 'Europe',
  'Germany': 'Europe',
  'Denmark': 'Europe',
  'Sweden': 'Europe',
  'Norway': 'Europe',
  'Finland': 'Europe',
  'Estonia': 'Europe',
  'Latvia': 'Europe',
  'Lithuania': 'Europe',
  'Poland': 'Europe',
  'Switzerland': 'Europe',
  'Austria': 'Europe',
  // Mediterranean
  'Italy': 'Mediterranean',
  'Greece': 'Mediterranean',
  'Croatia': 'Mediterranean',
  'Montenegro': 'Mediterranean',
  'Albania': 'Mediterranean',
  'Slovenia': 'Mediterranean',
  'Malta': 'Mediterranean',
  'Cyprus': 'Mediterranean',
  'Monaco': 'Mediterranean',
  'Corsica': 'Mediterranean',
  'Sardinia': 'Mediterranean',
  'Sicily': 'Mediterranean',
  'Turkey': 'Mediterranean',
  'Israel': 'Mediterranean',
  'Lebanon': 'Mediterranean',
  'Egypt': 'Mediterranean',
  'Libya': 'Mediterranean',
  'Tunisia': 'Mediterranean',
  'Algeria': 'Mediterranean',
  'Morocco': 'Mediterranean',
  // Middle East
  'United Arab Emirates': 'Middle East',
  'Oman': 'Middle East',
  'Qatar': 'Middle East',
  'Bahrain': 'Middle East',
  'Kuwait': 'Middle East',
  'Saudi Arabia': 'Middle East',
  'Yemen': 'Middle East',
  // Asia Pacific
  'Maldives': 'Asia Pacific',
  'India': 'Asia Pacific',
  'Sri Lanka': 'Asia Pacific',
  'Thailand': 'Asia Pacific',
  'Malaysia': 'Asia Pacific',
  'Singapore': 'Asia Pacific',
  'Indonesia': 'Asia Pacific',
  'Philippines': 'Asia Pacific',
  'Vietnam': 'Asia Pacific',
  'Cambodia': 'Asia Pacific',
  'Myanmar': 'Asia Pacific',
  'Brunei': 'Asia Pacific',
  'Hong Kong': 'Asia Pacific',
  'Japan': 'Asia Pacific',
  'Taiwan': 'Asia Pacific',
  'South Korea': 'Asia Pacific',
  'China': 'Asia Pacific',
  'Australia': 'Asia Pacific',
  'New Zealand': 'Asia Pacific',
  'Fiji': 'Asia Pacific',
  'Vanuatu': 'Asia Pacific',
  'Tonga': 'Asia Pacific',
  'Samoa': 'Asia Pacific',
  'French Polynesia': 'Asia Pacific',
  'New Caledonia': 'Asia Pacific',
  'Papua New Guinea': 'Asia Pacific',
  // Africa
  'South Africa': 'Africa',
  'Mozambique': 'Africa',
  'Tanzania': 'Africa',
  'Kenya': 'Africa',
  'Seychelles': 'Africa',
  'Mauritius': 'Africa',
  'Réunion': 'Africa',
  'Madagascar': 'Africa',
  'Namibia': 'Africa',
  'Nigeria': 'Africa',
  'Ghana': 'Africa',
  'Senegal': 'Africa',
  'Ivory Coast': 'Africa',
};
